### ISSUE TITLE
remove unsafe in msbwt2::string_util::convert_itos

### ISSUE THREAD

**Issue by Ebedthan** [HudsonAlpha/rust-msbwt#6]
Hi,

I was wondering why not use directly [from_utf8_lossy](https://doc.rust-lang.org/std/string/struct.String.html#method.from_utf8_lossy) which "returns a [Cow<'a, str>](https://doc.rust-lang.org/std/borrow/enum.Cow.html). If our byte slice is invalid UTF-8, then we need to insert the replacement characters, which will change the size of the string, and hence, require a String. But if it’s already valid UTF-8, we don’t need a new allocation. This return type allows us to handle both cases."

So except we are sure that [`convert_itos`](https://github.com/HudsonAlpha/rust-msbwt/blob/main/src/string_util.rs#L84-L88) can take as input non-valid utf8, using `from_utf8_lossy` also provides a non-allocating way of doing what we want, and we also reduce the amount of unsafe in the code...

What is your advice?

Anicet

**Comment by holtjma** [comment]
I was probably unaware of the function when that was initially developed.  If they are functionally equivalent, then whichever is more efficient is preferable.  I suspect that when compiled, they are equivalent in terms of speed.

**Comment by holtjma** [comment]
Just to add to this, it seems they are _not_ the same.  I have this same function over in [fmlrc2](https://github.com/HudsonAlpha/rust-fmlrc/blob/master/src/string_util.rs) with a benchmark already baked in.

This was the current method:
```
convert_itos            time:   [34.132 ns 34.209 ns 34.293 ns]                          
                        change: [-0.5054% -0.3042% -0.1099%] (p = 0.00 < 0.05)
                        Change within noise threshold.
Found 3 outliers among 100 measurements (3.00%)
  3 (3.00%) high mild
```
And the other approach using `String::from_utf8_lossy(&ret_vec).to_string()`:
```
convert_itos            time:   [70.684 ns 70.710 ns 70.738 ns]                         
                        change: [+106.59% +106.98% +107.38%] (p = 0.00 < 0.05)
                        Performance has regressed.
Found 10 outliers among 100 measurements (10.00%)
  1 (1.00%) high mild
  9 (9.00%) high severe
```
I suspect that the method is injecting another copy operation.

**Comment by Ebedthan** [comment]
Great! So are you willing to trade some speed for safe code or do you think it is not worth it?

**Comment by holtjma** [comment]
In this particular instance, I would keep the speed since there are unit tests and the input to the unsafe block is fully controlled.
